- name: "Pre-fact-gathering Setup"
  hosts: all
  gather_facts: false

  tasks:
  - name: "Install Python (required for fact gathering)"
    become: true
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: "Installation"
  hosts: all
  tags:
  - deploy

  tasks:
  - name: "Install prerequisites"
    become: true
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
    - awscli
    - openjdk-8-jre-headless
    - python-pip

  - name: "Create minecraft root directory"
    become: true
    file:
      path: /minecraft
      owner: ubuntu
      group: ubuntu
      state: directory

  - name: "Mount NVMe device to minecraft directory"
    become: true
    become_user: root
    shell: |
        mkfs.ext4 /dev/nvme0n1
        mount -t ext4 /dev/nvme0n1 /minecraft
    ignore_errors: true

  - name: "Clone git repo into minecraft directory"
    git:
      repo: https://github.com/gerhalt/mining-camp.git
      dest: /minecraft/mining-camp

  - name: "Install Python requirements"
    become: true
    shell: |
      pip install -r '/minecraft/mining-camp/requirements.txt'

  - name: "Retrieve server tarball from S3"
    s3:
      bucket: "{{s3_bucket}}"
      object: "/{{server_name}}/{{server_file}}"
      dest: "/minecraft/{{server_file}}"
      mode: get

  - name: "Extract and install server"
    shell: |
      cd /minecraft
      tar -xzvf {{server_file}}

  - name: "Install prospector config"
    copy:
      src: "files/prospector.cfg"
      dest: "/minecraft/prospector.cfg"

  - name: "Install minecraft server config"
    copy:
      src: "files/server.properties"
      dest: "/minecraft/{{server_name}}/config/server.properties"

  - name: "Add backup script to crontab"
    cron:
      name: "minecraft backup monitor"
      minute: "*/5"
      job: "/minecraft/mining-camp/utilities/prospector.py backup"

  - name: "Add emergency shutdown script to crontab"
    cron:
      name: "spot instance shutdown monitor"
      job: "/minecraft/mining-camp/utilities/shutdown.sh"

  - name: "Start server bootstrap script"
    shell: |
      /minecraft/mining-camp/utilities/bootstrap.sh /minecraft/{{server_name}}

  - name: "Assign elastic ip"
    local_action: shell aws ec2 associate-address --instance-id {{ec2_id}} --allocation-id {{minecraft_eip_alloc_id}}
